name: Send Daily Job Email

on:
  schedule:
    - cron: '0 16 * * *'  # Runs every day at 9:30 PM IST (4:00 PM UTC)
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: pip install --upgrade pip

    - name: Run Email Script
      env:
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      run: python daily_job_emailer.py
